spring.application.name=proyecto1
server.port=8081

# Metadata de la aplicación (leída por @ConfigurationProperties)
# La versión se sincroniza automáticamente con el pom.xml gracias a @project.version@
app.info.name=Gestor de Inventario
app.info.version=@project.version@
app.info.environment=default
app.info.developer-email=andy.laglaguano@empresa.com

# Perfil activo por defecto
spring.profiles.active=dev
